# CI de Nível 1 - Disparo manual a partir de 1 clique

name: "Execução Manual - Testes Web (M6_AutomacaoDeTestesEmWeb)"

on:
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install project dependencies
        working-directory: ./M6_AutomacaoDeTestesEmWeb
        run: npm install

      - name: Run Cypress tests
        working-directory: ./M6_AutomacaoDeTestesEmWeb
        run: npx cypress run